### PR TITLE
check of location region criteria was added to factory

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
fixes https://github.com/OHDSI/WebAPI/issues/1668

### CODE REVIEW

**Comment by chrisknoll** [comment]
Hi, @ssuvorov-fls.  Would you be able to add a test case for this? Doesn't need to cover all the other missing test coverage for the other checkers, but I'd like to make sure that we have test cases covering any change made in a PR. 

Thank you!

**Review by chrisknoll — APPROVED** [review]

**Comment by chrisknoll** [comment]
Sorry, I was working to close out these PRs for the next relase and forgot I asked for test cases.

@ssuvorov-fls : Can you please make it an action item to add tests for these checks to the repo?

**Comment by ssuvorov-fls** [comment]
@chrisknoll 
> Sorry, I was working to close out these PRs for the next relase and forgot I asked for test cases.
> 
> @ssuvorov-fls : Can you please make it an action item to add tests for these checks to the repo?

Tests for unused concepts have been added

**Comment by chrisknoll** [comment]
Thank you.  I think I'd prefer a smaller test case JSON (there's 4k lines of json in those 2 tests) but I appreciate the effort. In future tests, try to make the minimum viable dataset to test with.

**Review by chrisknoll — APPROVED** [review]

**Pull request merged**
